spring.datasource.url=jdbc:mysql://localhost:3306/predictive_control
spring.datasource.username=root
spring.datasource.password=Akshay2413

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
